{"uid":"4b4757e66a1912dae1a509f688f20b0f","name":"categories","children":[{"name":"Test defects","children":[{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107eaaee0>: Failed to establish a new connection: [Errno 61] Connection refused'))","children":[{"name":"test1_loginUserExisted","uid":"757ad21ce47c77b1","parentUid":"8e4ff94cb3db4746c89bf8594b3273d3","status":"broken","time":{"start":1690252106948,"stop":1690252106951,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":3,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"8e4ff94cb3db4746c89bf8594b3273d3"},{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107bdbca0>: Failed to establish a new connection: [Errno 61] Connection refused'))","children":[{"name":"test2_LogOutUserExisted","uid":"430a83c600dd089f","parentUid":"939d428ef7c551fed1e8ea0c5d6d4c1e","status":"broken","time":{"start":1690252107737,"stop":1690252107740,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":3,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"939d428ef7c551fed1e8ea0c5d6d4c1e"}],"uid":"bdbf199525818fae7a8651db9eafe741"}]}